# Generated by Django 3.2 on 2021-04-18 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, help_text='This subject should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('profile_pic', models.ImageField(blank=True, max_length=255, null=True, upload_to='profile', verbose_name='Profile picture')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('phone_number', models.CharField(blank=True, max_length=255, verbose_name='Phone Number (with country code)')),
                ('is_active', models.BooleanField(default=True, help_text='This user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subject', verbose_name='Subjects')),
            ],
            options={
                'verbose_name': 'Teached',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
