# Generated by Django 3.2 on 2021-04-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210419_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(default='img/avatar5.png', upload_to='profile', verbose_name='Profile picture'),
        ),
    ]
