# Generated by Django 3.2 on 2021-04-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_teacher_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='room_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Room Number'),
        ),
    ]
